# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  BUILD_NUMBER: $(Build.BuildId)

steps:
- task: Cache@2
  inputs:
    key: 'gradle | "$(Agent.OS)"'
    path: '$(GRADLE_USER_HOME)'
    restoreKeys: 'gradle'
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    options: '--no-daemon --build-cache'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    tasks: 'clean build deobfJar'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build/libs'
    ArtifactName: 'Release'
    publishLocation: 'Container'